# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - roadmap.md
  - docs/c/latest/index.html
  - docs/cpp/latest/index.html

exclude:
  - script_*
